### ISSUE TITLE
create-character errors out at end

### ISSUE THREAD

**Issue by bitsandbooks** [canismarko/dungeon-sheets#17]
I set up a venv and installed dungeonsheets. I ran through the `create-character` utility and when I got to the end, instead of writing out my character.py file, I got the following error:

    Traceback (most recent call last):
      File "/usr/local/bin/create-character", line 10, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.7/site-packages/dungeonsheets/create_character.py", line 383, in main
        my_app.save_character()
      File "/usr/local/lib/python3.7/site-packages/dungeonsheets/create_character.py", line 79, in save_character
        ).get_template(src_filename).render(context)
      File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 187, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: character_template.txt

Anyone else get this?

**Comment by jacobdmoore** [comment]
Getting the same issue.

**Comment by PJBrs** [comment]
I think this bug is not present anymore (if it ever was).

**Comment by canismarko** [comment]
Probably true. I'm going to close it then. Thanks @PJBrs 

@bitsandbooks Feel free to reopen if you have more steps to reproduce.
