### ISSUE TITLE
Hand crossbow isn't defined

### ISSUE THREAD

**Issue by geckon** [canismarko/dungeon-sheets#81]
I'm getting the following error while trying to add a hand crossbow to a character:
```
Traceback (most recent call last):
  File "/path/lib/python3.8/site-packages/dungeonsheets/character.py", line 646, in wield_weapon
    NewWeapon = findattr(weapons, weapon)
  File "/path/lib/python3.8/site-packages/dungeonsheets/stats.py", line 38, in findattr
    raise AttributeError(f'{obj} has no attribute {name}')
AttributeError: <module 'dungeonsheets.weapons' from '/path/lib/python3.8/site-packages/dungeonsheets/weapons.py'> has no attribute crossbow, hand

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/some-path/dungeon-sheets/dungeonsheets/create_character.py", line 739, in <module>
    main()
  File "/some-path/dungeon-sheets/dungeonsheets/create_character.py", line 731, in main
    my_app.run()
  File "/path/lib/python3.8/site-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/path/lib/python3.8/site-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/path/lib/python3.8/site-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/path/lib/python3.8/site-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/path/lib/python3.8/site-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/path/lib/python3.8/site-packages/npyscreen/fmActionForm.py", line 77, in edit
    self.edit_return_value = self.on_ok()
  File "/some-path/dungeon-sheets/dungeonsheets/create_character.py", line 594, in on_ok
    self.parentApp.character.wield_weapon(wpn)
  File "/path/lib/python3.8/site-packages/dungeonsheets/character.py", line 648, in wield_weapon
    raise AttributeError(f'Weapon "{weapon}" is not defined')
AttributeError: Weapon "crossbow, hand" is not defined
```

**Comment by DanRoscigno** [comment]
@geckon in the Ranger 2 example this is how that crossbow is used:
```
weapons = ('rapier', 'hand crossbow')
```

Did you have a `crossbow, hand` in there?  Try it like above.

**Comment by geckon** [comment]
You're right @DanRoscigno, if I use it in the `.py` file to generate sheet later, it works. I'm talking about the step-by-step process implemented in `create_character.py`. If you select the offered hand crossbow there, you'll get the traceback above.

**Comment by canismarko** [comment]
Thanks @DanRoscigno @geckon
